# 作業

思考一下我們前面有提到圖片是矩陣，但維度可能會不一樣
例如灰階圖只有兩個維度，RGB 彩圖則有 3 個維度

假如今天我們把 RGB 3 個維度拆開來看會有甚麼不同的效果呢？

In [8]:
import cv2
import numpy as np

img = cv2.imread(r'C:\Users\o8ma1\Desktop\CVandDL_Marathon\lena.png')
print(img.shape)

#method1_one channel to gray. 
img_B = img[:, :, 0]
img_G = img[:, :, 1]
img_R = img[:, :, 2]
print(img_B)

#method2_one channel to gray also.
B,G,R = cv2.split(img)
print(B)

#method3_three channels to b,g,r, respectively.
zeros = np.zeros(img.shape[:2], dtype=img.dtype)
print(cv2.merge([B,zeros,zeros]))
print(cv2.merge([B,zeros,zeros]).shape)

while True:
    
    cv2.imshow('B1',img_B)
    cv2.imshow('G1',img_G)
    cv2.imshow('R1',img_R)
    cv2.imshow('B2', B)
    cv2.imshow('G2', G)
    cv2.imshow('R2', R)
    cv2.imshow('B3', cv2.merge([B,zeros,zeros]))
    cv2.imshow('G3', cv2.merge([zeros,G,zeros]))
    cv2.imshow('R3', cv2.merge([zeros,zeros,R]))
    
    k=cv2.waitKey(0)
    
    if(k == 27):
        cv2.destroyAllWindows()
        break

(512, 512, 3)
[[125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 ...
 [ 60  60  58 ...  84  76  79]
 [ 57  57  62 ...  79  81  81]
 [ 57  57  62 ...  79  81  81]]
[[125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 [125 125 133 ... 122 110  90]
 ...
 [ 60  60  58 ...  84  76  79]
 [ 57  57  62 ...  79  81  81]
 [ 57  57  62 ...  79  81  81]]
[[[125   0   0]
  [125   0   0]
  [133   0   0]
  ...
  [122   0   0]
  [110   0   0]
  [ 90   0   0]]

 [[125   0   0]
  [125   0   0]
  [133   0   0]
  ...
  [122   0   0]
  [110   0   0]
  [ 90   0   0]]

 [[125   0   0]
  [125   0   0]
  [133   0   0]
  ...
  [122   0   0]
  [110   0   0]
  [ 90   0   0]]

 ...

 [[ 60   0   0]
  [ 60   0   0]
  [ 58   0   0]
  ...
  [ 84   0   0]
  [ 76   0   0]
  [ 79   0   0]]

 [[ 57   0   0]
  [ 57   0   0]
  [ 62   0   0]
  ...
  [ 79   0   0]
  [ 81   0   0]
  [ 81   0   0]]

 [[ 57   0   0]
  [ 57   0   0]
  [ 62   0   0]
  ...
  [ 79   0   0]
  [ 81